### PR TITLE
Added support for livereload >=2.4.1

### LINKED ISSUE #39: Bug with livereload==2.4.1
Hi, folks!

I've got some issues today and my short investigation showed me that the root cause is in new version of `livereload` lib. Please, check my output:

```bash
(venv)Romans-Mac-Book-Air:docs romanmogilatov$ sphinx-autobuild . _build/html/
Traceback (most recent call last):
  File "/Users/romanmogilatov/ets-labs/dependency_injector/venv/bin/sphinx-autobuild", line 11, in <module>
    sys.exit(main())
  File "/Users/romanmogilatov/ets-labs/dependency_injector/venv/lib/python2.7/site-packages/sphinx_autobuild/__init__.py", line 280, in main
    server.watch(srcdir, builder)
  File "/Users/romanmogilatov/ets-labs/dependency_injector/venv/lib/python2.7/site-packages/livereload/server.py", line 203, in watch
    self.watcher.watch(filepath, func, delay, ignore=ignore)
TypeError: watch() got an unexpected keyword argument 'ignore'
(venv)Romans-Mac-Book-Air:docs romanmogilatov$ pip show livereload
---
Name: livereload
Version: 2.4.1
Location: /Users/romanmogilatov/ets-labs/dependency_injector/venv/lib/python2.7/site-packages
Requires: tornado, six
(venv)Romans-Mac-Book-Air:docs romanmogilatov$ pip install livereload==2.4.0
Downloading/unpacking livereload==2.4.0
  Downloading livereload-2.4.0-py2.py3-none-any.whl
Requirement already satisfied (use --upgrade to upgrade): tornado in /Users/romanmogilatov/ets-labs/dependency_injector/venv/lib/python2.7/site-packages (from livereload==2.4.0)
Requirement already satisfied (use --upgrade to upgrade): six in /Users/romanmogilatov/ets-labs/dependency_injector/venv/lib/python2.7/site-packages (from livereload==2.4.0)
Requirement already satisfied (use --upgrade to upgrade): backports.ssl-match-hostname in /Users/romanmogilatov/ets-labs/dependency_injector/venv/lib/python2.7/site-packages (from tornado->livereload==2.4.0)
Requirement already satisfied (use --upgrade to upgrade): singledispatch in /Users/romanmogilatov/ets-labs/dependency_injector/venv/lib/python2.7/site-packages (from tornado->livereload==2.4.0)
Requirement already satisfied (use --upgrade to upgrade): certifi in /Users/romanmogilatov/ets-labs/dependency_injector/venv/lib/python2.7/site-packages (from tornado->livereload==2.4.0)
Requirement already satisfied (use --upgrade to upgrade): backports-abc>=0.4 in /Users/romanmogilatov/ets-labs/dependency_injector/venv/lib/python2.7/site-packages (from tornado->livereload==2.4.0)
Installing collected packages: livereload
  Found existing installation: livereload 2.4.1
    Uninstalling livereload:
      Successfully uninstalled livereload
Successfully installed livereload
Cleaning up...
(venv)Romans-Mac-Book-Air:docs romanmogilatov$ sphinx-autobuild . _build/html/
[I 160119 15:57:45 server:271] Serving on http://127.0.0.1:8000
[I 160119 15:57:45 handlers:58] Start watching changes
[I 160119 15:57:45 handlers:60] Start detecting changes
c^C[I 160119 15:57:48 server:291] Shutting down...
(venv)Romans-Mac-Book-Air:docs romanmogilatov$
```

### LINKED ISSUE #40: Error when running sphinx-autobuild in python 3.5 on Windows 7
I installed sphinx-autobuild using 

```
pip install sphinx-autobuild
```

I am using anaconda python:

```
$ python
Python 3.5.1 |Anaconda 2.4.0 (64-bit)| (default, Dec  7 2015, 15:00:12) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
```

Here is the traceback:

```
$ sphinx-autobuild source build/html
Traceback (most recent call last):
  File "k:\python\anaconda\lib\runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "k:\python\anaconda\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "K:\Python\Anaconda\Scripts\sphinx-autobuild.exe\__main__.py", line 9, in <module>
  File "k:\python\anaconda\lib\site-packages\sphinx_autobuild\__init__.py", line 280, in main
    server.watch(srcdir, builder)
  File "k:\python\anaconda\lib\site-packages\livereload\server.py", line 203, in watch
    self.watcher.watch(filepath, func, delay, ignore=ignore)
TypeError: watch() got an unexpected keyword argument 'ignore'
```

### PR DESCRIPTION
**Pull request by rodcloutier**
This PR is intended to fix compatibility with livereload version >= 2.4.1
This version of livereload changed the API for watchers. It now expected a keyword parameter called `ignore`.

Fix #39 
Fix #40

### CODE REVIEW

**Comment by rodcloutier** [comment]
Let me know if the PR is targeted at the right branch.

**Comment by momijiame** [comment]
LGTM!

**Comment by GaretJax** [comment]
Thanks for the fix!
