### ISSUE TITLE
Error when running sphinx-autobuild in python 3.5 on Windows 7

### ISSUE THREAD

**Issue by breisfeld** [GaretJax/sphinx-autobuild#40]
I installed sphinx-autobuild using 

```
pip install sphinx-autobuild
```

I am using anaconda python:

```
$ python
Python 3.5.1 |Anaconda 2.4.0 (64-bit)| (default, Dec  7 2015, 15:00:12) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
```

Here is the traceback:

```
$ sphinx-autobuild source build/html
Traceback (most recent call last):
  File "k:\python\anaconda\lib\runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "k:\python\anaconda\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "K:\Python\Anaconda\Scripts\sphinx-autobuild.exe\__main__.py", line 9, in <module>
  File "k:\python\anaconda\lib\site-packages\sphinx_autobuild\__init__.py", line 280, in main
    server.watch(srcdir, builder)
  File "k:\python\anaconda\lib\site-packages\livereload\server.py", line 203, in watch
    self.watcher.watch(filepath, func, delay, ignore=ignore)
TypeError: watch() got an unexpected keyword argument 'ignore'
```

**Comment by rmk135** [comment]
Duplicate of #39

**Comment by rmk135** [comment]
As a quick fix you can do:

```bash
pip install livereload==2.4.0
```

**Comment by breisfeld** [comment]
Thanks. I'll give it a try.

By the way, kudos for this excellent package! It saves so much time and effort.

**Comment by eblur** [comment]
I've attempted the livereload==2.4.0 work around and I still get a very similar error.

```
$ python
Python 2.7.10 |Anaconda 2.3.0 (x86_64)| (default, Sep 15 2015, 14:29:08) 
[GCC 4.2.1 (Apple Inc. build 5577)] on darwin
```

```
$ sphinx-autobuild . _build_html
Traceback (most recent call last):
  File "//anaconda/bin/sphinx-autobuild", line 11, in <module>
    sys.exit(main())
  File "//anaconda/lib/python2.7/site-packages/sphinx_autobuild/__init__.py", line 280, in main
    server.watch(srcdir, builder)
  File "//anaconda/lib/python2.7/site-packages/livereload/server.py", line 203, in watch
    self.watcher.watch(filepath, func, delay, ignore=ignore)
TypeError: watch() got an unexpected keyword argument 'ignore'
```

**Comment by vairamsvsjdo** [comment]
can this be deployed to pip as a dot release?
Is it available in pip? If yes, what is the version number
